general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
normal = { family = "MesloLGSNerdFontMono", style = "Regular" }
size = 10
